export const FOODS = [
  {
    id: 1,
    name: "Jollof Rice + Chicken",
    emoji: "🍚",
    desc: "Nigeria's finest party jollof with smoky tomato stew and seasoned grilled chicken.",
    price: 2800,
    oldPrice: 3200,
    tag: "local",
    badge: "hot",
    rating: "4.9",
    time: "20 min",
    cals: "680 kcal",
    rest: "Ajiwumi Kitchen",
  },
  {
    id: 2,
    name: "Grilled Chicken Combo",
    emoji: "🍗",
    desc: "Crispy golden chicken pieces with spicy pepper sauce, coleslaw & fried plantain.",
    price: 3200,
    oldPrice: null,
    tag: "fast food",
    badge: "pop",
    rating: "4.8",
    time: "15 min",
    cals: "720 kcal",
    rest: "Chicken Republic",
  },
  {
    id: 3,
    name: "Peri-Peri Chicken Burger",
    emoji: "🍔",
    desc: "Flame-grilled chicken fillet, peri-peri mayo, lettuce and pickles on a toasted bun.",
    price: 2500,
    oldPrice: 2800,
    tag: "fast food",
    badge: "new",
    rating: "4.7",
    time: "12 min",
    cals: "640 kcal",
    rest: "Chicken Republic",
  },
  {
    id: 4,
    name: "Moi Moi + Boiled Egg",
    emoji: "🥘",
    desc: "Steamed bean pudding with boiled egg and crayfish — a classic Nigerian breakfast.",
    price: 800,
    oldPrice: null,
    tag: "local",
    badge: "",
    rating: "4.6",
    time: "10 min",
    cals: "320 kcal",
    rest: "Ajiwumi Kitchen",
  },
  {
    id: 5,
    name: "Grilled Tilapia + Eba",
    emoji: "🐟",
    desc: "Whole grilled tilapia in local spices with smooth eba and rich egusi soup.",
    price: 3500,
    oldPrice: 4000,
    tag: "local",
    badge: "hot",
    rating: "4.8",
    time: "25 min",
    cals: "580 kcal",
    rest: "Eyitayo Restaurant",
  },
  {
    id: 6,
    name: "Smoothie Fruit Bowl",
    emoji: "🍓",
    desc: "Tropical fruit blend topped with granola, chia seeds and honey drizzle.",
    price: 1500,
    oldPrice: null,
    tag: "healthy",
    badge: "heal",
    rating: "4.8",
    time: "8 min",
    cals: "280 kcal",
    rest: "Green Corner",
  },
  {
    id: 7,
    name: "Fried Rice + Plantain",
    emoji: "🍛",
    desc: "Seasoned fried rice with mixed veggies and sweet fried ripe plantain.",
    price: 2500,
    oldPrice: 2800,
    tag: "local",
    badge: "pop",
    rating: "4.7",
    time: "18 min",
    cals: "620 kcal",
    rest: "Ajiwumi Kitchen",
  },
  {
    id: 8,
    name: "Spicy Indomie + Egg",
    emoji: "🍜",
    desc: "Noodles cooked with egg, vegetables and our special spicy pepper blend.",
    price: 1000,
    oldPrice: null,
    tag: "snacks",
    badge: "",
    rating: "4.5",
    time: "10 min",
    cals: "430 kcal",
    rest: "Eyitayo Restaurant",
  },
  {
    id: 9,
    name: "Chapman Cocktail",
    emoji: "🥤",
    desc: "Campus classic — fanta, sprite, grenadine, cucumber & fresh oranges.",
    price: 700,
    oldPrice: null,
    tag: "drinks",
    badge: "",
    rating: "4.9",
    time: "5 min",
    cals: "180 kcal",
    rest: "Green Corner",
  },
  {
    id: 10,
    name: "Chicken Shawarma",
    emoji: "🌯",
    desc: "Juicy grilled chicken, fresh veggies, garlic sauce wrapped in warm flatbread.",
    price: 1800,
    oldPrice: 2000,
    tag: "snacks",
    badge: "hot",
    rating: "4.9",
    time: "12 min",
    cals: "540 kcal",
    rest: "Kapital Chicken",
  },
  {
    id: 11,
    name: "Caesar Salad",
    emoji: "🥗",
    desc: "Romaine lettuce, parmesan, croutons, grilled chicken strips and caesar dressing.",
    price: 1800,
    oldPrice: null,
    tag: "healthy",
    badge: "heal",
    rating: "4.7",
    time: "10 min",
    cals: "340 kcal",
    rest: "Green Corner",
  },
  {
    id: 12,
    name: "Pepper Soup",
    emoji: "🍲",
    desc: "Deeply aromatic catfish pepper soup with local spices — perfect for any weather.",
    price: 2200,
    oldPrice: null,
    tag: "local",
    badge: "new",
    rating: "4.8",
    time: "20 min",
    cals: "310 kcal",
    rest: "Eyitayo Restaurant",
  },
  {
    id: 13,
    name: "Continental Breakfast",
    emoji: "🍳",
    desc: "Eggs, toast, baked beans, sausage and fresh juice — start the day right.",
    price: 2800,
    oldPrice: null,
    tag: "healthy",
    badge: "",
    rating: "4.7",
    time: "15 min",
    cals: "560 kcal",
    rest: "EATWELL Restaurant",
  },
  {
    id: 14,
    name: "Veggie Wrap",
    emoji: "🥙",
    desc: "Grilled veggies, hummus, feta cheese and rocket in a warm tortilla wrap.",
    price: 1600,
    oldPrice: null,
    tag: "healthy",
    badge: "heal",
    rating: "4.6",
    time: "10 min",
    cals: "380 kcal",
    rest: "EATWELL Restaurant",
  },
  {
    id: 15,
    name: "Grilled Chicken Strips",
    emoji: "🍖",
    desc: "Tender marinated chicken strips with peri-peri dipping sauce and wedges.",
    price: 2600,
    oldPrice: 3000,
    tag: "fast food",
    badge: "pop",
    rating: "4.8",
    time: "14 min",
    cals: "590 kcal",
    rest: "Kapital Chicken",
  },
  {
    id: 16,
    name: "Zobo + Ginger Drink",
    emoji: "🧃",
    desc: "Refreshing chilled hibiscus drink blended with ginger, pineapple & mint.",
    price: 600,
    oldPrice: null,
    tag: "drinks",
    badge: "",
    rating: "4.7",
    time: "5 min",
    cals: "95 kcal",
    rest: "Green Corner",
  },
];

export const RESTS = [
  {
    name: "Green Corner",
    emoji: "🌿",
    banner: "linear-gradient(135deg,#00C853,#00D4C8)",
    tags: ["Healthy", "Salads", "Smoothies", "Juices"],
    rating: "4.8",
    time: "10 min",
    orders: "1.1K+",
    open: true,
  },
  {
    name: "Ajiwumi Kitchen",
    emoji: "🍲",
    banner: "linear-gradient(135deg,#FF5C00,#FF3CAC)",
    tags: ["Local Cuisine", "Rice", "Soups", "Stew"],
    rating: "4.9",
    time: "15 min",
    orders: "2.3K+",
    open: true,
  },
  {
    name: "Chicken Republic",
    emoji: "🍗",
    banner: "linear-gradient(135deg,#e63900,#ff9500)",
    tags: ["Chicken", "Burgers", "Fast Food"],
    rating: "4.8",
    time: "12 min",
    orders: "3.5K+",
    open: true,
  },
  {
    name: "Kapital Chicken",
    emoji: "🍖",
    banner: "linear-gradient(135deg,#7B2FFF,#FF3CAC)",
    tags: ["Grilled Chicken", "Shawarma", "Combos"],
    rating: "4.7",
    time: "18 min",
    orders: "980",
    open: true,
  },
  {
    name: "EATWELL Restaurant",
    emoji: "🍽️",
    banner: "linear-gradient(135deg,#1a6b3a,#2ecc71)",
    tags: ["Continental", "Breakfast", "Healthy"],
    rating: "4.9",
    time: "20 min",
    orders: "1.8K+",
    open: true,
  },
  {
    name: "Eyitayo Restaurant",
    emoji: "🥘",
    banner: "linear-gradient(135deg,#C9A800,#FF5C00)",
    tags: ["Nigerian Cuisine", "Soups", "Swallow"],
    rating: "4.8",
    time: "15 min",
    orders: "1.4K+",
    open: true,
  },
];

export const CATEGORIES = [
  { key: "all", label: "All", emoji: "" },
  { key: "local", label: "Local", emoji: "🍲" },
  { key: "fast food", label: "Fast Food", emoji: "🍔" },
  { key: "snacks", label: "Snacks", emoji: "🥪" },
  { key: "healthy", label: "Healthy", emoji: "🥗" },
  { key: "drinks", label: "Drinks", emoji: "🥤" },
];

export const HERO_STATS = [
  { value: "2,400+", label: "Happy Students" },
  { value: "6", label: "Partner Restaurants" },
  { value: "~15 min", label: "Avg Delivery" },
  { value: "4.9 ★", label: "Avg Rating" },
];

export const STEPS = [
  {
    num: "01",
    title: "Sign Up / Log In",
    text: "Create your free student account or sign in to get started instantly.",
    tone: "s1",
  },
  {
    num: "02",
    title: "Pick a Restaurant",
    text: "Browse all campus restaurants and choose your favourite spot.",
    tone: "s2",
  },
  {
    num: "03",
    title: "Add to Cart & Pay",
    text: "Customise your order, apply promo codes, and pay securely.",
    tone: "s3",
  },
  {
    num: "04",
    title: "Track & Enjoy",
    text: "Watch your order live and receive it fresh at your location.",
    tone: "s4",
  },
];

export const PROMOS = [
  {
    code: "NEWSTUDENT50",
    title: "50% OFF",
    label: "First Order",
    text: "New to CampusBite? Welcome — half off your first meal!",
    emoji: "🎉",
    tone: "p1",
  },
  {
    code: "LUNCHFREE",
    title: "Free Delivery",
    label: "Weekday Special",
    text: "Order Mon–Fri 11AM–2PM above ₦1,500 and pay no delivery fee.",
    emoji: "🚀",
    tone: "p2",
  },
  {
    code: "STUDYCOMBO",
    title: "Combo ₦2,200",
    label: "Study Fuel",
    text: "Any main dish + cold drink at our special student bundle price.",
    emoji: "📚",
    tone: "p3",
  },
];

export const REVIEWS = [
  {
    stars: "★★★★★",
    text: "Literally saved me during exam week. Food arrives hot and on time every single time!",
    name: "Amara K.",
    role: "200L Computer Science",
    avatar: "👩‍💻",
    tone: "rgba(255,92,0,.18)",
  },
  {
    stars: "★★★★★",
    text: "The jollof rice from Ajiwumi Kitchen hits different! Delivery always within 20 mins.",
    name: "Tunde B.",
    role: "400L Engineering",
    avatar: "🧑‍🎓",
    tone: "rgba(0,200,83,.18)",
  },
  {
    stars: "★★★★★",
    text: "Promo codes are a blessing on a student budget. Will definitely keep using CampusBite!",
    name: "Chioma E.",
    role: "300L Medicine",
    avatar: "👩‍⚕️",
    tone: "rgba(123,47,255,.18)",
  },
  {
    stars: "★★★★★",
    text: "As a lecturer I use it for dept lunches. Group order feature is super convenient!",
    name: "Dr. Okonkwo",
    role: "Senior Lecturer, Sciences",
    avatar: "👨‍🏫",
    tone: "rgba(0,212,200,.18)",
  },
  {
    stars: "★★★★★",
    text: "The tracking feature is so satisfying. I know exactly when food will arrive!",
    name: "Fatima M.",
    role: "500L Pharmacy",
    avatar: "👩‍🔬",
    tone: "rgba(255,60,172,.18)",
  },
  {
    stars: "★★★★★",
    text: "Fast, reliable, easy to use. Chicken Republic on campus has never been so accessible!",
    name: "Segun F.",
    role: "100L Fine Arts",
    avatar: "🧑‍🎨",
    tone: "rgba(255,214,0,.18)",
  },
];

export const RECENT_ORDERS = [
  {
    emoji: "🍚",
    name: "Jollof Rice + Chicken",
    rest: "Ajiwumi Kitchen",
    price: "₦2,800",
  },
  {
    emoji: "🍗",
    name: "Grilled Chicken Combo",
    rest: "Chicken Republic",
    price: "₦3,200",
  },
  {
    emoji: "🌯",
    name: "Chicken Shawarma",
    rest: "Kapital Chicken",
    price: "₦1,800",
  },
];

export const ABOUT_STATS = [
  { value: "2,400+", label: "Active Users", color: "var(--orange)" },
  { value: "6", label: "Restaurants", color: "var(--yellow)" },
  { value: "50K+", label: "Orders Delivered", color: "var(--green)" },
  { value: "4.9★", label: "Avg Rating", color: "var(--purple)" },
];

export const CONTACT_INFO = [
  { icon: "📍", label: "Address", value: "SOMEWHERE " },
  { icon: "📞", label: "Phone", value: "0800-CAMPUS-BITE" },
  { icon: "📧", label: "Email", value: "joelhabila1000@gmail.com" },
  {
    icon: "🕐",
    label: "Hours",
    value: "Mon–Fri: 7AM–10PM · Sat–Sun: 9AM–9PM",
  },
];
